micronaut:
  application:
    name: micronaut-crud
datasources:
  default:
    url: jdbc:mysql://127.0.0.1:3306/mn_playground
    username: root
    password: SQL2023!
    driver-class-name: com.mysql.cj.jdbc.Driver
flyway:
  datasources:
    default:
      enabled: true