name: Build and Test Micronaut App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-timeout=30s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # This is a commonly used OpenJDK build
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to start..."
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -u root -pSQL2023! --silent; then
              echo "MySQL is up and running"
              exit 0
            fi
            sleep 2
          done
          echo "MySQL did not start in time" && exit 1

      - name: Build and Test
        run: ./gradlew clean build --refresh-dependencies

      - name: Package JAR File
        run: ./gradlew shadowJar

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: micronaut-app
          path: build/libs/*.jar
